### ISSUE TITLE
Does not run on macOS

### ISSUE THREAD

**Issue by elmimmo** [UniBoDS4H/Image-Alignment#2]
Steps to reproduce (as per “Installation” at <https://github.com/UniBoDS4H/IA/releases/download/1.0.0b/DS4H-IA_Documentation_20231106.pdf>):

1. Download <https://github.com/UniBoDS4H/IA/releases/download/1.0.0b/DS4H_ImageAlignment-1.0.0-all.jar>
2. Put it inside /Applications/ImageJ.app/plugins/
3. Launch ImageJ and open 2 images.
4. Go to menu Plugins ▸ DS4H Image Alignment ▸ DS4H-IA

Actual results:

1. A new window titled “Log” comes up which says:

```
[libopencv_alphamat.4.7.0.dylib, libopencv_aruco.4.7.0.dylib, libopencv_barcode.4.7.0.dylib, libopencv_bgsegm.4.7.0.dylib, libopencv_bioinspired.4.7.0.dylib, libopencv_calib3d.4.7.0.dylib, libopencv_ccalib.4.7.0.dylib, libopencv_core.4.7.0.dylib, libopencv_datasets.4.7.0.dylib, libopencv_dnn.4.7.0.dylib, libopencv_dnn_objdetect.4.7.0.dylib, libopencv_dnn_superres.4.7.0.dylib, libopencv_dpm.4.7.0.dylib, libopencv_face.4.7.0.dylib, libopencv_features2d.4.7.0.dylib, libopencv_flann.4.7.0.dylib, libopencv_freetype.4.7.0.dylib, libopencv_fuzzy.4.7.0.dylib, libopencv_gapi.4.7.0.dylib, libopencv_hfs.4.7.0.dylib, libopencv_highgui.4.7.0.dylib, libopencv_img_hash.4.7.0.dylib, libopencv_imgcodecs.4.7.0.dylib, libopencv_imgproc.4.7.0.dylib, libopencv_intensity_transform.4.7.0.dylib, libopencv_java470.dylib, libopencv_line_descriptor.4.7.0.dylib, libopencv_mcc.4.7.0.dylib, libopencv_ml.4.7.0.dylib, libopencv_objdetect.4.7.0.dylib, libopencv_optflow.4.7.0.dylib, libopencv_phase_unwrapping.4.7.0.dylib, libopencv_photo.4.7.0.dylib, libopencv_plot.4.7.0.dylib, libopencv_quality.4.7.0.dylib, libopencv_rapid.4.7.0.dylib, libopencv_reg.4.7.0.dylib, libopencv_rgbd.4.7.0.dylib, libopencv_saliency.4.7.0.dylib, libopencv_sfm.4.7.0.dylib, libopencv_shape.4.7.0.dylib, libopencv_stereo.4.7.0.dylib, libopencv_stitching.4.7.0.dylib, libopencv_structured_light.4.7.0.dylib, libopencv_superres.4.7.0.dylib, libopencv_surface_matching.4.7.0.dylib, libopencv_text.4.7.0.dylib, libopencv_tracking.4.7.0.dylib, libopencv_video.4.7.0.dylib, libopencv_videoio.4.7.0.dylib, libopencv_videostab.4.7.0.dylib, libopencv_viz.4.7.0.dylib, libopencv_wechat_qrcode.4.7.0.dylib, libopencv_xfeatures2d.4.7.0.dylib, libopencv_ximgproc.4.7.0.dylib, libopencv_xobjdetect.4.7.0.dylib, libopencv_xphoto.4.7.0.dylib]
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_alphamat.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_aruco.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_barcode.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_bgsegm.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_bioinspired.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_calib3d.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_ccalib.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_core.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_datasets.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_dnn.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_dnn_objdetect.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_dnn_superres.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_dpm.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_face.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_features2d.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_flann.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_freetype.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_fuzzy.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_gapi.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_hfs.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_highgui.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_img_hash.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_imgcodecs.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_imgproc.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_intensity_transform.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_java470.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_line_descriptor.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_mcc.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_ml.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_objdetect.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_optflow.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_phase_unwrapping.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_photo.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_plot.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_quality.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_rapid.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_reg.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_rgbd.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_saliency.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_sfm.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_shape.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_stereo.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_stitching.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_structured_light.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_superres.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_surface_matching.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_text.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_tracking.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_video.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_videoio.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_videostab.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_viz.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_wechat_qrcode.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_xfeatures2d.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_ximgproc.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_xobjdetect.4.7.0.dylib
file name: /var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_xphoto.4.7.0.dylib
```

2. A new window titled Exception comes up which says:

```
ImageJ 1.54i; Java 1.8.0_345 [64-bit]; Mac OS X 10.16; 119MB of 3000MB (3%)
 
java.lang.UnsatisfiedLinkError: /private/var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_java470.dylib: dlopen(/private/var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_java470.dylib, 0x0001): Library not loaded: @rpath/libopencv_xphoto.407.dylib
  Referenced from: <D0A40E92-FA06-3212-A522-9A33428EC678> /private/var/folders/yb/_0t9qp3519sdz6kw14c82fn80000gn/T/DS4HOpenCV_MAC2069775494444435530/libopencv_java470.dylib
  Reason: tried: '/usr/local/lib/libopencv_xphoto.407.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libopencv_xphoto.407.dylib' (no such file), '/usr/local/opt/brew/Cellar/opencv/4.7.0_4/lib/libopencv_xphoto.407.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/brew/Cellar/opencv/4.7.0_4/lib/libopencv_xphoto.407.dylib' (no such file), '/usr/local/lib/libopencv_xphoto.407.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libopencv_xphoto.407.dylib' (no such file), '
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:811)
	at java.lang.System.load(System.java:1088)
	at com.ds4h.model.util.opencvManager.opencvLoader.OpenCVLoader.loadMacIntel(OpenCVLoader.java:144)
	at com.ds4h.model.util.opencvManager.opencvLoader.OpenCVLoader.loadOpenCV(OpenCVLoader.java:49)
	at com.ds4h.controller.opencvController.OpencvController.loadLibrary(OpencvController.java:19)
	at com.ds4h.imagej.Image_Alignment.run(Image_Alignment.java:28)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)


Notes:

iMac18,3
CPU Intel Core i5 3,5 GHz 4 cores
macOS 13.6.6 (22G630) Ventura
$ java —version
   java 11 2018-09-25
   Java(TM) SE Runtime Environment 18.9 (build 11+28)
   Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
$ opencv_version -v
General configuration for OpenCV 4.9.0 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            /tmp/opencv-20240409-77071-ef9tvv/opencv-4.9.0/opencv_contrib/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2023-12-27T16:46:55Z
    Host:                        Darwin 22.6.0 x86_64
    CMake:                       3.29.1
    CMake generator:             Unix Makefiles
    CMake build tool:            gmake
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3 SSSE3
      requested:                 SSSE3
      required:                  SSSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (16 files):         + SSE4_1
      SSE4_2 (1 files):          + SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (8 files):             + SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (36 files):           + SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (5 files):      + SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      YES
    C++ standard:                17
    C++ Compiler:                clang++  (ver 15.0.0.15000100)
    C++ flags (Release):         -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-copy -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-copy -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  clang
    C flags (Release):           -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -mssse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,-dead_strip  
    Linker flags (Debug):        -Wl,-dead_strip  
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 alphamat aruco bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dnn_superres dpm face features2d flann freetype fuzzy gapi hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot python3 quality rapid reg rgbd saliency sfm shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab viz wechat_qrcode xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    hdf world
    Disabled by dependency:      -
    Unavailable:                 cannops cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv java julia matlab ovis python2 ts
    Applications:                apps
    Documentation:               NO
    Non-free algorithms:         YES

  GUI:                           COCOA
    Cocoa:                       YES
    VTK support:                 YES (ver 9.3.0)

  Media I/O: 
    ZLib:                        /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/lib/libz.tbd (ver 1.2.11)
    JPEG:                        /usr/local/lib/libjpeg.dylib (ver 80)
    WEBP:                        /usr/local/lib/libwebp.dylib (ver encoder: 0x020f)
    PNG:                         /usr/local/lib/libpng.dylib (ver 1.6.43)
    TIFF:                        /usr/local/lib/libtiff.dylib (ver 42 / 4.6.0)
    JPEG 2000:                   OpenJPEG (ver 2.5.2)
    OpenEXR:                     OpenEXR::OpenEXR (ver 3.2.4)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    FFMPEG:                      YES
      avcodec:                   YES (60.31.102)
      avformat:                  YES (60.16.100)
      avutil:                    YES (58.29.100)
      swscale:                   YES (7.5.100)
      avresample:                NO
    AVFoundation:                YES

  Parallel framework:            TBB (ver 2021.11 interface 12110)

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2021.9.1 [2021.9.1]
           at:                   /tmp/opencv-20240409-77071-ef9tvv/opencv-4.9.0/build_shared/3rdparty/ippicv/ippicv_mac/icv
    Intel IPP IW:                sources (2021.9.1)
              at:                /tmp/opencv-20240409-77071-ef9tvv/opencv-4.9.0/build_shared/3rdparty/ippicv/ippicv_mac/iw
    Lapack:                      YES (/usr/local/opt/openblas/lib/libopenblas.dylib)
    OpenVINO:                    YES (2024.0.0)
    Eigen:                       YES (ver 3.4.0)
    Custom HAL:                  NO
    Protobuf:                    /usr/local/lib/libprotobuf.26.1.0.dylib (26.1.0)
    Flatbuffers:                 builtin/3rdparty (23.5.9)

  OpenCL:                        YES (no extra features)
    Include path:                NO
    Link libraries:              -framework OpenCL

  Python 3:
    Interpreter:                 /usr/local/opt/python@3.12/bin/python3.12 (ver 3.12.2)
    Libraries:                   /usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/lib/libpython3.12.dylib (ver 3.12.2)
    numpy:                       /usr/local/lib/python3.12/site-packages/numpy/core/include (ver 1.26.4)
    install path:                lib/python3.12/site-packages/cv2/python-3.12

  Python (for build):            /usr/local/opt/python@3.12/bin/python3.12

  Java:                          
    ant:                         NO
    Java:                        NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    /usr/local/Cellar/opencv/4.9.0_7
-----------------------------------------------------------------
```

**Comment by MatteoIorio11** [comment]
Dear user, thank you for using our plugin! I just want to inform you that I have introduced the support for ARM architectures in the latest release

**Comment by elmimmo** [comment]
Thank you. You do not seem to have taken into account the standard path onto which opencv is symlinked by Homebrew (probably the most popular package manager for Macs) on Apple Silicon:

```
% brew --prefix opencv
/opt/homebrew/opt/opencv/
```
with its lib path therefore being `/opt/homebrew/opt/opencv/lib/`.

You also seemingly expect a specific version (405) which is now pretty old (2019?) and not easy (or advisable?) to install. I do not know about other platforms or package managers, but Homebrew symlinks the version numbered lib (such as `libopencv_xphoto.413.dylib`) to the version-agnostic one `libopencv_xphoto.dylib`.

```
ImageJ 1.54g; Java 13.0.6 [64-bit]; Mac OS X 15.7.3; 212MB of 3000MB (7%)
 
java.lang.UnsatisfiedLinkError: /private/var/folders/_j/f5lgtc2n1tlc8fy7xlffdlsh0000gn/T/DS4H_OpenCVLibrary5825647342015359430.dylib: dlopen(/private/var/folders/_j/f5lgtc2n1tlc8fy7xlffdlsh0000gn/T/DS4H_OpenCVLibrary5825647342015359430.dylib, 0x0001): Library not loaded: @rpath/libopencv_xphoto.405.dylib
  Referenced from: <95273C8A-CB53-340C-B3CE-B6B0D57A44CD> /private/var/folders/_j/f5lgtc2n1tlc8fy7xlffdlsh0000gn/T/DS4H_OpenCVLibrary5825647342015359430.dylib
  Reason: tried: '/usr/local/lib/libopencv_xphoto.405.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libopencv_xphoto.405.dylib' (no such file), '/Users/matteoiorio/Desktop/opencv/build_opencv/lib/libopencv_xphoto.405.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/matteoiorio/Desktop/opencv/build_opencv/lib/libopencv_xphoto.405.dylib' (no such file), '/usr/local/lib/libopencv_xphoto.405.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libopencv_xphoto.405.dylib' (no such file), '/Users/matteoiorio/Desktop/openc
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
	at java.base/java.lang.Runtime.load0(Runtime.java:745)
	at java.base/java.lang.System.load(System.java:1873)
	at com.ds4h.model.util.opencvManager.opencvLoader.OpenCVLoader.alreadyLoaded(OpenCVLoader.java:99)
	at com.ds4h.model.util.opencvManager.opencvLoader.OpenCVLoader.loadLib(OpenCVLoader.java:75)
	at com.ds4h.model.util.opencvManager.opencvLoader.OpenCVLoader.loadMacArm(OpenCVLoader.java:55)
	at com.ds4h.model.util.opencvManager.opencvLoader.OpenCVLoader.loadOpenCV(OpenCVLoader.java:39)
	at com.ds4h.controller.opencvController.OpencvController.loadLibrary(OpencvController.java:19)
	at com.ds4h.imagej.Image_Alignment.run(Image_Alignment.java:29)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by MatteoIorio11** [comment]
Hi, thank you for reporting this! I have not taken into account `brew` because I have compiled `OpenCV` by myself and injected into the project as you can see from the files stored in the resources directory. It seems very strange that in the error it is reported this path: "'/Users/matteoiorio/Desktop/opencv/build_opencv/lib/libopencv_xphoto.405.dylib'", I will look to this and keep you informed.


In the meantime I thank you again for your support :)

**Comment by MatteoIorio11** [comment]
By the way I saw from your original message what you tried to do with our plugin. You do not need to start ImageJ and then open two images, but you have to open imagej -> open our plugin -> import at least two images (by using "File" -> "Load Images") from the menu bar

**Comment by MatteoIorio11** [comment]
Could you also please tell me exactly what you did ? Because I have just installed the latest version of ImageJ, moved our plugin into the plugins directory and everything seems to work fine

**Comment by elmimmo** [comment]
> Could you also please tell me exactly what you did ? Because I have just installed the latest version of ImageJ, moved our plugin into the plugins directory and everything seems to work fine

Well, don’t you have your build of opencv where my log says and the very version it says? I don’t, for the reasons I described.

**Comment by MatteoIorio11** [comment]
The opencv library is bundled with the DS4H jar, so there is no need to use anything custom made (or installed using brew). I have developed our internal opencv loader that gets the correct opencv library from its own resources (in this case the jar itself)

One thing that you could do is trying to go to the temporary path: /private/var/folders/_j/f5lgtc2n1tlc8fy7xlffdlsh0000gn/T/ and remove all the DS4H*.dylib files. Only after this try again with our plugin. 

Do you have the same error on Fiji ?

**Comment by elmimmo** [comment]
> exactly what you did ?

1. Installed ImageJ with Homebrew: `brew install --cask imagej`
2. Manually downloaded Fiji
3. Downloaded `DS4H_ImageAlignment-1.2.1-all.jar` from releases.
4. Just in case it had quarantine xattr, removed all `xattr -c DS4H_ImageAlignment-1.2.1-all.jar`
5. Dropped `DS4H_ImageAlignment-1.2.1-all.jar` into `/Applications/ImageJ.app/plugins` and `${HOME}/Downloads/Fiji/plugins`
6. Opened both.
7. Menu Plugins ▸ DS4H Image Alignment ▸ DS4H-IA
8. Log window appears with error

> go to the temporary path: /private/var/folders/_j/f5lgtc2n1tlc8fy7xlffdlsh0000gn/T/ and remove all the DS4H*.dylib files. Only after this try again with our plugin.

Same result.

> Do you have the same error on Fiji ?

Yes.

If you have any other suggestions of what I could try, do not hesitate to say. Thanks for the interest.

This is my current environment (different from when I started the issue):

- MacBook Air 13 inch, M3, 2024
- 16 GB RAM
- macOS 15.7.3 (24G419) Sequoia
- ImageJ 1.54g; bundled Java 13.0.6
- (Fiji is Just) ImageJ 2.16.0; bundled Java 21.0.7
- DS4H_ImageAlignment-1.2.1-all.jar

Same result with:

- MacBook Pro 14 inch M2 Pro 2023
- 32 GB RAM
- Rest, same.

**Comment by MatteoIorio11** [comment]
Hi @elmimmo!
Thank you for reporting me this, I have tried exactly what you did by recreating each step (downloading ImageJ with brew etc etc) and everything seems to work fine

I will still try to find the reason why it does not work on your machine 


I will keep you posted

**Comment by MatteoIorio11** [comment]
I have recreated the error, I am going to fix it and deliver a new version

**Comment by MatteoIorio11** [comment]
Hi @elmimmo!
I have created a new release for the plugin with the fix, let me know if it works!

**Comment by elmimmo** [comment]
Seems to work fine! Now I only need to decipher what does what 😅
